apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: txdx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: txdx
    app.kubernetes.io/part-of: byoc-app-nkvu
  name: txdxsieh
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: txdx
    weight: null
status: {}
